"""empty message

Revision ID: 98ccaa673ad4
Revises: bcf6d75afe28
Create Date: 2020-06-10 12:02:55.134789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ccaa673ad4'
down_revision = 'bcf6d75afe28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
